### ISSUE TITLE
502 on vimawesome.com

### ISSUE THREAD

**Issue by asm0dey** [divad12/vim-awesome#67]

**Comment by divad12** [comment]
Fixed — restarted gunicorn. Not sure why it crashed. Error from logs:

> 2015-06-05 05:42:02 [5751] [INFO] Unhandled exception in main loop:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 174, in run
    self.sleep()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 308, in sleep
    oldest = min(w.tmp.last_update() for w in worker_values)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 308, in <genexpr>
    oldest = min(w.tmp.last_update() for w in worker_values)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/workertmp.py", line 50, in last_update
    return os.fstat(self._tmp.fileno()).st_ctime
ValueError: I/O operation on closed file

**Comment by divad12** [comment]
Thanks for reporting!

**Comment by asm0dey** [comment]
Thanks for fixing :)
